# Helper script to plot benchmark results from a CSV file
# generated by the simulation_benchmarks Rust benchmark, which
# saves the results to target/simulation_benchmarks/<benchmark_name>.csv

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def main():
    if len(sys.argv) != 2:
        print("Usage: python plot_benchmarks.py <path_to_csv>")
        sys.exit(1)

    file_path = Path(sys.argv[1])

    if not file_path.is_file():
        print(f"Error: File '{file_path}' does not exist.")
        sys.exit(1)

    plot_benchmark(file_path)


def plot_benchmark(file_path: Path):
    df = pd.read_csv(file_path)
    required_columns = {"n", "gravity", "integrator", "time_ms"}
    if not required_columns.issubset(df.columns):
        raise ValueError(f"CSV must contain columns: {required_columns}")

    # aggregate repeated runs (mean time per n/gravity/integrator)
    grouped = (
        df.groupby(["n", "gravity", "integrator"], as_index=False)["time_ms"]
        .mean()
        .sort_values("n")
    )

    # create label column for each gravity/integrator combination
    grouped["method"] = grouped["gravity"] + " / " + grouped["integrator"]

    plt.figure()

    for method, subset in grouped.groupby("method"):
        plt.plot(subset["n"], subset["time_ms"], marker="o", label=method)

    plt.xlabel("Number of Bodies")
    plt.ylabel("Time (ms)")
    plt.title("Simulation Time vs Number of Bodies")
    plt.legend()
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
